// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dopwoputiudjihwwkhyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvcHdvcHV0aXVkamlod3draHluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzQ1MjMsImV4cCI6MjA2MjgxMDUyM30.qIwY8VuEMNrtTpF95fbiDic1LzmvK3hgKQgu52ICo-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);